# spring.application.name=Message exchanger

# Connecting the spring boot to the postgreSQL

spring.datasource.url=jdbc:postgresql://localhost:5432/messageDB
spring.datasource.username=postgres
spring.datasource.password=vijayi wfh
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
